export { HomePage } from './home'
export { AboutUsPage } from './aboutUs'
export { NotFoundPage } from './notFound'
export { LoginPage } from './login'
export { RegistrationPage } from './registration'
export { RegistrationSuccess } from './registrationSuccess'
export { RecoveryPage } from './recovery'
export { RecoveryCodePage } from './recoveryCode'
export { RecoverySuccessPage } from './recoverySuccess'
export { ContactsPage } from './contacts'
export { ProductPage } from './Product'
export { CheckoutPage } from './checkout'
export { CatalogPage } from './catalog'

